# Faithfulness

FaithfulnessCorrelation: True # -1 to 1
fc_nr_runs: 100
fc_subset_size: 224
fc_perturb_baseline: "black"

FaithfulnessEstimate: True
fe_features_in_step: 224
fe_perturb_baseline: "black"

MonotonicityCorrelation: True
mc_nr_samples: 10
mc_features_in_step: 3136
mc_perturb_baseline: "uniform"

PixelFlipping: True
pf_features_in_step: 224
pf_perturb_baseline: "black"

RegionPerturbation: True
rp_patch_size: 18
rp_regions_evaluation: 20
rp_perturb_baseline: "uniform"

InsertionDeletion: True
id_pixel_batch_size: 50
id_sigma: 40.0
id_kernel_size: 19

IROF: True
irof_segmentation_method: "slic"
irof_perturb_baseline: "mean"

ROAD: True
road_noise: 0.1
road_percentages_max: 100

Sufficiency: True
su_threshold: 0.6


# Robustness

LocalLipschitzEstimate: True
lle_nr_samples: 5
lle_perturb_std: 0.1
lle_perturb_mean: 0.0

MaxSensitivity: True
ms_nr_samples: 10
ms_lower_bound: 0.2

Continuity: True
co_patch_size: 56
co_nr_steps: 20
co_perturb_baseline: "uniform"

RelativeInputStability: True
ris_nr_samples: 10

RelativeOutputStability: True
ros_nr_samples: 10

RelativeRepresentationStability: True
rrs_nr_samples: 10

Infidelity: True
in_n_perturb_samples: 50

# Usability

Sparseness: True

Complexity: True

EffectiveComplexity: True
ec_eps: 0.01

# util
normalise: True
device: "cuda:0"