# Single:
occlusion: True
occ_strides: 1
occ_sliding_window_shapes: 3
occ_baselines: 0
perturbations_per_eval: 80

lime: True
lime_alpha: 4.0
lime_n_samples: 10
lime_perturbations_per_eval: 1

kernel_shap: True
ks_baselines: 0
ks_n_samples: 10
ks_perturbations_per_eval: 1

saliency: True

input_x_gradient: True

guided_backprob: True

gcam: False

scam: False
scam_batch_size: 16

gcampp: False

ig: True
ig_baselines: 0
ig_n_steps: 16

eg: True
eg_n_samples: 16 # 80
eg_stdevs: 0.001 # 0.001

deeplift: True
dl_eps: 0.000000001
dl_baselines: 0


deeplift_shap: True

lrp: True
lrp_eps: 0.00001
lrp_gamma: 0.25

attention: True

